### ISSUE TITLE
Cannot use tox generated matrix; Azure Pipelines does not accept jobs with '-'

### ISSUE THREAD

**Issue by ahgraber** [tox-dev/azure-pipelines-template#12]
Sample tox envlist:
```ini
[tox]
# https://tox.readthedocs.io/en/latest/config.html#generative-envlist
envlist =
    clean,
    check,
    ; py{37,38}-np{18}-pd{0,2}-sci{14,16},  # test conflict btwn numpy, scipy, and c extensions
    ; py{37,38}-np{19,20}-pd{0,2}-sci{15,16},
    py{37,38}-np{18,19,20},
    py39,  # latest version of python, assume 'latest' for dependencies
    report,
    docs
```

Sample azure pipeline workflow:
```yml
resources:
  repositories:
    - repository: tox
      type: github
      endpoint: github
      name: tox-dev/azure-pipelines-template
      ref: refs/tags/0.2

jobs:
  - template: run-tox-env.yml@tox
    parameters:
      tox_version: ""
      jobs:
        check: null
        py37-np18:
        py37-np19:
        py37-np20:
        py38-np18:
        py38-np19:
        py38-np20:
        py39:
        coverage:
          with_toxenv: "report"
          for_envs: [py37-np18, py37-np19, py37-np20, py38-np18, py38-np19, py38-np20, py39]
        docs: null
```

Azure Pipelines error message:
![image](https://user-images.githubusercontent.com/24922003/123863659-da8b0e00-d8f7-11eb-9b04-007f9125a62e.png)
